[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"
watchPatterns = ["student-portal-frontend/**/*"]

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["nodejs-20_x"]
cmds = [
    "npm install -g npm@latest",
    "node -v"
]

[phases.build]
cmds = [
    "npm install",
    "npm run build"
]

[phases.deploy]
cmds = [
    "node server.js"
]

[variables]
NODE_VERSION = "20.11.1"
PORT = "3000"
NPM_VERSION = "10.2.4"
